# Generated by Django 5.2.8 on 2025-11-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='ar', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chapter_audios/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='books.chapter')),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='audio.reciter')),
            ],
        ),
        migrations.CreateModel(
            name='AudioTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(blank=True, help_text='End time in seconds', null=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='books.verse')),
                ('chapter_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='audio.chapteraudio')),
            ],
            options={
                'unique_together': {('chapter_audio', 'verse')},
            },
        ),
    ]
