# Generated by Django 5.2.8 on 2025-11-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
        ('books', '0002_book_tenant_alter_book_unique_together'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciters', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='chapteraudio',
            unique_together={('chapter', 'reciter')},
        ),
        migrations.AlterUniqueTogether(
            name='reciter',
            unique_together={('tenant', 'name')},
        ),
    ]
