# Generated by Django 5.2.8 on 2025-11-22 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
        ('books', '0001_initial'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='verse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.verse'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='chapter_audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.chapteraudio'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernote',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.verse'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'book', 'chapter', 'verse')},
        ),
        migrations.AlterUniqueTogether(
            name='playhistory',
            unique_together={('user', 'chapter_audio')},
        ),
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'verse')},
        ),
    ]
